blank_issues_enabled: false
contact_links:
    - name: Need help?
      url: https://github.com/bloomwalletio/bloom/discussions/categories/q-a
      about: Ask the community for help or support
    - name: Request a feature
      url: https://github.com/bloomwalletio/bloom/discussions/categories/ideas
      about: Propose a feature or enhancement in GitHub discussions
    - name: General feedback
      url: https://github.com/bloomwalletio/bloom/discussions/categories/general
      about: Leave us some feedback
    - name: Join our Discord
      url: https://discord.gg/RjX3jEc7K7
      about: Chat with the devs and the Bloom community
